[package]
name = "rfetch"
version = "0.1.0"
edition = "2021"
authors = ["NotCreative21"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.21.2"
